//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.ivp.srm.vendorapi.AlterLoggerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Info", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class Info : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private com.ivp.srm.vendorapi.AlterLoggerService.EventCategory EventIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private com.ivp.srm.vendorapi.AlterLoggerService.EStatus EventStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private com.ivp.srm.vendorapi.AlterLoggerService.EType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public com.ivp.srm.vendorapi.AlterLoggerService.EventCategory EventID {
            get {
                return this.EventIDField;
            }
            set {
                if ((this.EventIDField.Equals(value) != true)) {
                    this.EventIDField = value;
                    this.RaisePropertyChanged("EventID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public com.ivp.srm.vendorapi.AlterLoggerService.EStatus EventStatus {
            get {
                return this.EventStatusField;
            }
            set {
                if ((this.EventStatusField.Equals(value) != true)) {
                    this.EventStatusField = value;
                    this.RaisePropertyChanged("EventStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageDetails {
            get {
                return this.MessageDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageDetailsField, value) != true)) {
                    this.MessageDetailsField = value;
                    this.RaisePropertyChanged("MessageDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameDetails {
            get {
                return this.NameDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.NameDetailsField, value) != true)) {
                    this.NameDetailsField = value;
                    this.RaisePropertyChanged("NameDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public com.ivp.srm.vendorapi.AlterLoggerService.EType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventCategory", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    public enum EventCategory : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LogIn = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LogOut = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AppStart = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AppStop = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AppError = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SentMail = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReceivedMail = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PushToExternalSystem = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TaskTrigger = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TaskFinish = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TaskError = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataUpdate = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConfigurationUpdate = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        General = 14,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EStatus", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    public enum EStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Done = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Critical = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EType", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    public enum EType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Security = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Information = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Audit = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="filterInfo", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class filterInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> SelectedTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> SelectedType {
            get {
                return this.SelectedTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SelectedTypeField, value) != true)) {
                    this.SelectedTypeField = value;
                    this.RaisePropertyChanged("SelectedType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlterLoggerService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EventFired", ReplyAction="http://tempuri.org/IService1/EventFiredResponse")]
        void EventFired(com.ivp.srm.vendorapi.AlterLoggerService.Info info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterToList", ReplyAction="http://tempuri.org/IService1/RegisterToListResponse")]
        void RegisterToList(com.ivp.srm.vendorapi.AlterLoggerService.filterInfo finf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateList", ReplyAction="http://tempuri.org/IService1/UpdateListResponse")]
        void UpdateList(com.ivp.srm.vendorapi.AlterLoggerService.filterInfo finf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteFromList", ReplyAction="http://tempuri.org/IService1/DeleteFromListResponse")]
        void DeleteFromList(string UserID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : com.ivp.srm.vendorapi.AlterLoggerService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<com.ivp.srm.vendorapi.AlterLoggerService.IService1>, com.ivp.srm.vendorapi.AlterLoggerService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void EventFired(com.ivp.srm.vendorapi.AlterLoggerService.Info info) {
            base.Channel.EventFired(info);
        }
        
        public void RegisterToList(com.ivp.srm.vendorapi.AlterLoggerService.filterInfo finf) {
            base.Channel.RegisterToList(finf);
        }
        
        public void UpdateList(com.ivp.srm.vendorapi.AlterLoggerService.filterInfo finf) {
            base.Channel.UpdateList(finf);
        }
        
        public void DeleteFromList(string UserID) {
            base.Channel.DeleteFromList(UserID);
        }
    }
}
