//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace com.ivp.srm.vendorapi.bloombergServices.lite {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GetDataServiceSeiBinding", Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DLWSResponse))]
    public partial class GetDataService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBloombergDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback createViewDefinitionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getViewDefinitionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBloombergViewDefinitionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getViewNamesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBloombergViewNamesOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateViewDefinitionOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteViewDefinitionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFieldsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOverrideFieldsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GetDataService() {
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getDataCompletedEventHandler getDataCompleted;
        
        /// <remarks/>
        public event getBloombergDataCompletedEventHandler getBloombergDataCompleted;
        
        /// <remarks/>
        public event createViewDefinitionCompletedEventHandler createViewDefinitionCompleted;
        
        /// <remarks/>
        public event getViewDefinitionCompletedEventHandler getViewDefinitionCompleted;
        
        /// <remarks/>
        public event getBloombergViewDefinitionCompletedEventHandler getBloombergViewDefinitionCompleted;
        
        /// <remarks/>
        public event getViewNamesCompletedEventHandler getViewNamesCompleted;
        
        /// <remarks/>
        public event getBloombergViewNamesCompletedEventHandler getBloombergViewNamesCompleted;
        
        /// <remarks/>
        public event updateViewDefinitionCompletedEventHandler updateViewDefinitionCompleted;
        
        /// <remarks/>
        public event deleteViewDefinitionCompletedEventHandler deleteViewDefinitionCompleted;
        
        /// <remarks/>
        public event getFieldsCompletedEventHandler getFieldsCompleted;
        
        /// <remarks/>
        public event getOverrideFieldsCompletedEventHandler getOverrideFieldsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getDataResponse", Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
        public getDataResponse getData([System.Xml.Serialization.XmlElementAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")] getDataRequest getDataRequest) {
            object[] results = this.Invoke("getData", new object[] {
                        getDataRequest});
            return ((getDataResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getDataAsync(getDataRequest getDataRequest) {
            this.getDataAsync(getDataRequest, null);
        }
        
        /// <remarks/>
        public void getDataAsync(getDataRequest getDataRequest, object userState) {
            if ((this.getDataOperationCompleted == null)) {
                this.getDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDataOperationCompleted);
            }
            this.InvokeAsync("getData", new object[] {
                        getDataRequest}, this.getDataOperationCompleted, userState);
        }
        
        private void OngetDataOperationCompleted(object arg) {
            if ((this.getDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDataCompleted(this, new getDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getBloombergDataResponse", Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
        public getDataResponse getBloombergData([System.Xml.Serialization.XmlElementAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")] getDataRequest getBloombergDataRequest) {
            object[] results = this.Invoke("getBloombergData", new object[] {
                        getBloombergDataRequest});
            return ((getDataResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getBloombergDataAsync(getDataRequest getBloombergDataRequest) {
            this.getBloombergDataAsync(getBloombergDataRequest, null);
        }
        
        /// <remarks/>
        public void getBloombergDataAsync(getDataRequest getBloombergDataRequest, object userState) {
            if ((this.getBloombergDataOperationCompleted == null)) {
                this.getBloombergDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBloombergDataOperationCompleted);
            }
            this.InvokeAsync("getBloombergData", new object[] {
                        getBloombergDataRequest}, this.getBloombergDataOperationCompleted, userState);
        }
        
        private void OngetBloombergDataOperationCompleted(object arg) {
            if ((this.getBloombergDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBloombergDataCompleted(this, new getBloombergDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CreateViewDefinitionResponse", Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
        public CreateOrUpdateViewDefinitionResponse createViewDefinition([System.Xml.Serialization.XmlElementAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")] CreateOrUpdateViewDefinitionRequest CreateViewDefinitionRequest) {
            object[] results = this.Invoke("createViewDefinition", new object[] {
                        CreateViewDefinitionRequest});
            return ((CreateOrUpdateViewDefinitionResponse)(results[0]));
        }
        
        /// <remarks/>
        public void createViewDefinitionAsync(CreateOrUpdateViewDefinitionRequest CreateViewDefinitionRequest) {
            this.createViewDefinitionAsync(CreateViewDefinitionRequest, null);
        }
        
        /// <remarks/>
        public void createViewDefinitionAsync(CreateOrUpdateViewDefinitionRequest CreateViewDefinitionRequest, object userState) {
            if ((this.createViewDefinitionOperationCompleted == null)) {
                this.createViewDefinitionOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateViewDefinitionOperationCompleted);
            }
            this.InvokeAsync("createViewDefinition", new object[] {
                        CreateViewDefinitionRequest}, this.createViewDefinitionOperationCompleted, userState);
        }
        
        private void OncreateViewDefinitionOperationCompleted(object arg) {
            if ((this.createViewDefinitionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createViewDefinitionCompleted(this, new createViewDefinitionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetViewDefinitionResponse", Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
        public GetViewDefinitionResponse getViewDefinition([System.Xml.Serialization.XmlElementAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")] GetViewDefinitionRequest GetViewDefinitionRequest) {
            object[] results = this.Invoke("getViewDefinition", new object[] {
                        GetViewDefinitionRequest});
            return ((GetViewDefinitionResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getViewDefinitionAsync(GetViewDefinitionRequest GetViewDefinitionRequest) {
            this.getViewDefinitionAsync(GetViewDefinitionRequest, null);
        }
        
        /// <remarks/>
        public void getViewDefinitionAsync(GetViewDefinitionRequest GetViewDefinitionRequest, object userState) {
            if ((this.getViewDefinitionOperationCompleted == null)) {
                this.getViewDefinitionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetViewDefinitionOperationCompleted);
            }
            this.InvokeAsync("getViewDefinition", new object[] {
                        GetViewDefinitionRequest}, this.getViewDefinitionOperationCompleted, userState);
        }
        
        private void OngetViewDefinitionOperationCompleted(object arg) {
            if ((this.getViewDefinitionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getViewDefinitionCompleted(this, new getViewDefinitionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetBloombergViewDefinitionResponse", Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
        public GetViewDefinitionResponse getBloombergViewDefinition([System.Xml.Serialization.XmlElementAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")] GetBloombergViewDefinitionRequest GetBloombergViewDefinitionRequest) {
            object[] results = this.Invoke("getBloombergViewDefinition", new object[] {
                        GetBloombergViewDefinitionRequest});
            return ((GetViewDefinitionResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getBloombergViewDefinitionAsync(GetBloombergViewDefinitionRequest GetBloombergViewDefinitionRequest) {
            this.getBloombergViewDefinitionAsync(GetBloombergViewDefinitionRequest, null);
        }
        
        /// <remarks/>
        public void getBloombergViewDefinitionAsync(GetBloombergViewDefinitionRequest GetBloombergViewDefinitionRequest, object userState) {
            if ((this.getBloombergViewDefinitionOperationCompleted == null)) {
                this.getBloombergViewDefinitionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBloombergViewDefinitionOperationCompleted);
            }
            this.InvokeAsync("getBloombergViewDefinition", new object[] {
                        GetBloombergViewDefinitionRequest}, this.getBloombergViewDefinitionOperationCompleted, userState);
        }
        
        private void OngetBloombergViewDefinitionOperationCompleted(object arg) {
            if ((this.getBloombergViewDefinitionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBloombergViewDefinitionCompleted(this, new getBloombergViewDefinitionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetViewNamesResponse", Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
        public GetViewNamesResponse getViewNames([System.Xml.Serialization.XmlElementAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")] GetViewNamesRequest GetViewNamesRequest) {
            object[] results = this.Invoke("getViewNames", new object[] {
                        GetViewNamesRequest});
            return ((GetViewNamesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getViewNamesAsync(GetViewNamesRequest GetViewNamesRequest) {
            this.getViewNamesAsync(GetViewNamesRequest, null);
        }
        
        /// <remarks/>
        public void getViewNamesAsync(GetViewNamesRequest GetViewNamesRequest, object userState) {
            if ((this.getViewNamesOperationCompleted == null)) {
                this.getViewNamesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetViewNamesOperationCompleted);
            }
            this.InvokeAsync("getViewNames", new object[] {
                        GetViewNamesRequest}, this.getViewNamesOperationCompleted, userState);
        }
        
        private void OngetViewNamesOperationCompleted(object arg) {
            if ((this.getViewNamesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getViewNamesCompleted(this, new getViewNamesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetBloombergViewNamesResponse", Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
        public GetViewNamesResponse getBloombergViewNames([System.Xml.Serialization.XmlElementAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")] GetBloombergViewNamesRequest GetBloombergViewNamesRequest) {
            object[] results = this.Invoke("getBloombergViewNames", new object[] {
                        GetBloombergViewNamesRequest});
            return ((GetViewNamesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getBloombergViewNamesAsync(GetBloombergViewNamesRequest GetBloombergViewNamesRequest) {
            this.getBloombergViewNamesAsync(GetBloombergViewNamesRequest, null);
        }
        
        /// <remarks/>
        public void getBloombergViewNamesAsync(GetBloombergViewNamesRequest GetBloombergViewNamesRequest, object userState) {
            if ((this.getBloombergViewNamesOperationCompleted == null)) {
                this.getBloombergViewNamesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBloombergViewNamesOperationCompleted);
            }
            this.InvokeAsync("getBloombergViewNames", new object[] {
                        GetBloombergViewNamesRequest}, this.getBloombergViewNamesOperationCompleted, userState);
        }
        
        private void OngetBloombergViewNamesOperationCompleted(object arg) {
            if ((this.getBloombergViewNamesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBloombergViewNamesCompleted(this, new getBloombergViewNamesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("UpdateViewDefinitionResponse", Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
        public CreateOrUpdateViewDefinitionResponse updateViewDefinition([System.Xml.Serialization.XmlElementAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")] CreateOrUpdateViewDefinitionRequest UpdateViewDefinitionRequest) {
            object[] results = this.Invoke("updateViewDefinition", new object[] {
                        UpdateViewDefinitionRequest});
            return ((CreateOrUpdateViewDefinitionResponse)(results[0]));
        }
        
        /// <remarks/>
        public void updateViewDefinitionAsync(CreateOrUpdateViewDefinitionRequest UpdateViewDefinitionRequest) {
            this.updateViewDefinitionAsync(UpdateViewDefinitionRequest, null);
        }
        
        /// <remarks/>
        public void updateViewDefinitionAsync(CreateOrUpdateViewDefinitionRequest UpdateViewDefinitionRequest, object userState) {
            if ((this.updateViewDefinitionOperationCompleted == null)) {
                this.updateViewDefinitionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateViewDefinitionOperationCompleted);
            }
            this.InvokeAsync("updateViewDefinition", new object[] {
                        UpdateViewDefinitionRequest}, this.updateViewDefinitionOperationCompleted, userState);
        }
        
        private void OnupdateViewDefinitionOperationCompleted(object arg) {
            if ((this.updateViewDefinitionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateViewDefinitionCompleted(this, new updateViewDefinitionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("DeleteViewDefinitionResponse", Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
        public Response deleteViewDefinition([System.Xml.Serialization.XmlElementAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")] DeleteViewDefinitionRequest DeleteViewDefinitionRequest) {
            object[] results = this.Invoke("deleteViewDefinition", new object[] {
                        DeleteViewDefinitionRequest});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void deleteViewDefinitionAsync(DeleteViewDefinitionRequest DeleteViewDefinitionRequest) {
            this.deleteViewDefinitionAsync(DeleteViewDefinitionRequest, null);
        }
        
        /// <remarks/>
        public void deleteViewDefinitionAsync(DeleteViewDefinitionRequest DeleteViewDefinitionRequest, object userState) {
            if ((this.deleteViewDefinitionOperationCompleted == null)) {
                this.deleteViewDefinitionOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteViewDefinitionOperationCompleted);
            }
            this.InvokeAsync("deleteViewDefinition", new object[] {
                        DeleteViewDefinitionRequest}, this.deleteViewDefinitionOperationCompleted, userState);
        }
        
        private void OndeleteViewDefinitionOperationCompleted(object arg) {
            if ((this.deleteViewDefinitionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteViewDefinitionCompleted(this, new deleteViewDefinitionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetFieldsResponse", Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
        public GetFieldsResponse getFields([System.Xml.Serialization.XmlElementAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")] GetFieldsRequest GetFieldsRequest) {
            object[] results = this.Invoke("getFields", new object[] {
                        GetFieldsRequest});
            return ((GetFieldsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getFieldsAsync(GetFieldsRequest GetFieldsRequest) {
            this.getFieldsAsync(GetFieldsRequest, null);
        }
        
        /// <remarks/>
        public void getFieldsAsync(GetFieldsRequest GetFieldsRequest, object userState) {
            if ((this.getFieldsOperationCompleted == null)) {
                this.getFieldsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFieldsOperationCompleted);
            }
            this.InvokeAsync("getFields", new object[] {
                        GetFieldsRequest}, this.getFieldsOperationCompleted, userState);
        }
        
        private void OngetFieldsOperationCompleted(object arg) {
            if ((this.getFieldsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFieldsCompleted(this, new getFieldsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetOverrideFieldsResponse", Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
        public GetOverrideFieldsResponse getOverrideFields([System.Xml.Serialization.XmlElementAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")] GetOverrideFieldsRequest GetOverrideFieldsRequest) {
            object[] results = this.Invoke("getOverrideFields", new object[] {
                        GetOverrideFieldsRequest});
            return ((GetOverrideFieldsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getOverrideFieldsAsync(GetOverrideFieldsRequest GetOverrideFieldsRequest) {
            this.getOverrideFieldsAsync(GetOverrideFieldsRequest, null);
        }
        
        /// <remarks/>
        public void getOverrideFieldsAsync(GetOverrideFieldsRequest GetOverrideFieldsRequest, object userState) {
            if ((this.getOverrideFieldsOperationCompleted == null)) {
                this.getOverrideFieldsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOverrideFieldsOperationCompleted);
            }
            this.InvokeAsync("getOverrideFields", new object[] {
                        GetOverrideFieldsRequest}, this.getOverrideFieldsOperationCompleted, userState);
        }
        
        private void OngetOverrideFieldsOperationCompleted(object arg) {
            if ((this.getOverrideFieldsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOverrideFieldsCompleted(this, new getOverrideFieldsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class getDataRequest : DLWSRequest {
        
        private string viewField;
        
        private DataItem[] fieldOverrideField;
        
        /// <remarks/>
        public string view {
            get {
                return this.viewField;
            }
            set {
                this.viewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fieldOverride")]
        public DataItem[] fieldOverride {
            get {
                return this.fieldOverrideField;
            }
            set {
                this.fieldOverrideField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class DataItem {
        
        private string fieldField;
        
        private string valueField;
        
        /// <remarks/>
        public string field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class GetOverrideFieldsRequest {
        
        private string mnemonicField;
        
        /// <remarks/>
        public string mnemonic {
            get {
                return this.mnemonicField;
            }
            set {
                this.mnemonicField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class FieldSearchCriteria {
        
        private string keywordField;
        
        private string mnemonicField;
        
        private DLCategory[] dlCategoriesField;
        
        private bool overridableField;
        
        private bool overridableFieldSpecified;
        
        private MarketSector[] marketsectorsField;
        
        /// <remarks/>
        public string keyword {
            get {
                return this.keywordField;
            }
            set {
                this.keywordField = value;
            }
        }
        
        /// <remarks/>
        public string mnemonic {
            get {
                return this.mnemonicField;
            }
            set {
                this.mnemonicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dlCategories")]
        public DLCategory[] dlCategories {
            get {
                return this.dlCategoriesField;
            }
            set {
                this.dlCategoriesField = value;
            }
        }
        
        /// <remarks/>
        public bool overridable {
            get {
                return this.overridableField;
            }
            set {
                this.overridableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool overridableSpecified {
            get {
                return this.overridableFieldSpecified;
            }
            set {
                this.overridableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("marketsectors")]
        public MarketSector[] marketsectors {
            get {
                return this.marketsectorsField;
            }
            set {
                this.marketsectorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public enum DLCategory {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Security Master")]
        SecurityMaster,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Derived Data")]
        DerivedData,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("End of Day Pricing")]
        EndofDayPricing,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("User Entered Info.")]
        UserEnteredInfo,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Corporate Actions")]
        CorporateActions,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Historical Time Series")]
        HistoricalTimeSeries,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public enum MarketSector {
        
        /// <remarks/>
        Govt,
        
        /// <remarks/>
        Corp,
        
        /// <remarks/>
        Mtge,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("M-Mkt")]
        MMkt,
        
        /// <remarks/>
        Muni,
        
        /// <remarks/>
        Pfd,
        
        /// <remarks/>
        Equity,
        
        /// <remarks/>
        Comdty,
        
        /// <remarks/>
        Index,
        
        /// <remarks/>
        Curncy,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class GetFieldsRequest {
        
        private FieldSearchCriteria criteriaField;
        
        /// <remarks/>
        public FieldSearchCriteria criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class DeleteViewDefinitionRequest {
        
        private string viewNameField;
        
        /// <remarks/>
        public string viewName {
            get {
                return this.viewNameField;
            }
            set {
                this.viewNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class GetBloombergViewNamesRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class GetViewNamesRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class GetBloombergViewDefinitionRequest {
        
        private string viewNameField;
        
        /// <remarks/>
        public string viewName {
            get {
                return this.viewNameField;
            }
            set {
                this.viewNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class GetViewDefinitionRequest {
        
        private string viewNameField;
        
        /// <remarks/>
        public string viewName {
            get {
                return this.viewNameField;
            }
            set {
                this.viewNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class FieldOptionsResponse {
        
        private bool realValueField;
        
        private bool realValueFieldSpecified;
        
        private int precisionField;
        
        private bool precisionFieldSpecified;
        
        private bool defaultPrecisionField;
        
        private bool defaultPrecisionFieldSpecified;
        
        /// <remarks/>
        public bool realValue {
            get {
                return this.realValueField;
            }
            set {
                this.realValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool realValueSpecified {
            get {
                return this.realValueFieldSpecified;
            }
            set {
                this.realValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int precision {
            get {
                return this.precisionField;
            }
            set {
                this.precisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precisionSpecified {
            get {
                return this.precisionFieldSpecified;
            }
            set {
                this.precisionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool defaultPrecision {
            get {
                return this.defaultPrecisionField;
            }
            set {
                this.defaultPrecisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool defaultPrecisionSpecified {
            get {
                return this.defaultPrecisionFieldSpecified;
            }
            set {
                this.defaultPrecisionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class FieldResponse {
        
        private string mnemonicField;
        
        private FieldOptionsResponse fieldOptionsField;
        
        private bool overrideField;
        
        private bool overrideFieldSpecified;
        
        private string fieldTypeField;
        
        private Status statusCodesField;
        
        /// <remarks/>
        public string mnemonic {
            get {
                return this.mnemonicField;
            }
            set {
                this.mnemonicField = value;
            }
        }
        
        /// <remarks/>
        public FieldOptionsResponse fieldOptions {
            get {
                return this.fieldOptionsField;
            }
            set {
                this.fieldOptionsField = value;
            }
        }
        
        /// <remarks/>
        public bool @override {
            get {
                return this.overrideField;
            }
            set {
                this.overrideField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool overrideSpecified {
            get {
                return this.overrideFieldSpecified;
            }
            set {
                this.overrideFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string fieldType {
            get {
                return this.fieldTypeField;
            }
            set {
                this.fieldTypeField = value;
            }
        }
        
        /// <remarks/>
        public Status statusCodes {
            get {
                return this.statusCodesField;
            }
            set {
                this.statusCodesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class Status {
        
        private int externalCodeField;
        
        private int internalCodeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public int externalCode {
            get {
                return this.externalCodeField;
            }
            set {
                this.externalCodeField = value;
            }
        }
        
        /// <remarks/>
        public int internalCode {
            get {
                return this.internalCodeField;
            }
            set {
                this.internalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateOrUpdateViewDefinitionResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetViewNamesResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetViewDefinitionResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class Response {
        
        private ViewAdminHeader dlwsHeaderField;
        
        private Status statusCodesField;
        
        /// <remarks/>
        public ViewAdminHeader dlwsHeader {
            get {
                return this.dlwsHeaderField;
            }
            set {
                this.dlwsHeaderField = value;
            }
        }
        
        /// <remarks/>
        public Status statusCodes {
            get {
                return this.statusCodesField;
            }
            set {
                this.statusCodesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class ViewAdminHeader : DLWSHeader {
        
        private DLCategory[] dlCategoriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("dlCategory", IsNullable=false)]
        public DLCategory[] dlCategories {
            get {
                return this.dlCategoriesField;
            }
            set {
                this.dlCategoriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ViewAdminHeader))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class DLWSHeader {
        
        private string webserviceField;
        
        private string operationField;
        
        private System.DateTime timestampField;
        
        private string dlwsRequestIdField;
        
        private string headerDataField;
        
        /// <remarks/>
        public string webservice {
            get {
                return this.webserviceField;
            }
            set {
                this.webserviceField = value;
            }
        }
        
        /// <remarks/>
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        public string dlwsRequestId {
            get {
                return this.dlwsRequestIdField;
            }
            set {
                this.dlwsRequestIdField = value;
            }
        }
        
        /// <remarks/>
        public string headerData {
            get {
                return this.headerDataField;
            }
            set {
                this.headerDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class CreateOrUpdateViewDefinitionResponse : Response {
        
        private FieldResponse[] fieldsField;
        
        private ViewOptions viewOptionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("field", IsNullable=false)]
        public FieldResponse[] fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
            }
        }
        
        /// <remarks/>
        public ViewOptions viewOptions {
            get {
                return this.viewOptionsField;
            }
            set {
                this.viewOptionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class ViewOptions {
        
        private DateFormat dateFormatField;
        
        private bool dateFormatFieldSpecified;
        
        /// <remarks/>
        public DateFormat dateFormat {
            get {
                return this.dateFormatField;
            }
            set {
                this.dateFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateFormatSpecified {
            get {
                return this.dateFormatFieldSpecified;
            }
            set {
                this.dateFormatFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public enum DateFormat {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mm/dd/yy")]
        mmddyy,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("dd/mm/yy")]
        ddmmyy,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("dd-mmm-yy")]
        ddmmmyy,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mm/dd/yyyy")]
        mmddyyyy,
        
        /// <remarks/>
        yyyymmdd,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("yy/dd/mm")]
        yyddmm,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("yyyy/dd/mm")]
        yyyyddmm,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("yy/mm/dd")]
        yymmdd,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("yyyy/mm/dd")]
        yyyymmdd1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("dd/mm/yyyy")]
        ddmmyyyy,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mm/yy/dd")]
        mmyydd,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mm/yyyy/dd")]
        mmyyyydd,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("dd/yy/mm")]
        ddyymm,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("dd/yyyy/mm")]
        ddyyyymm,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class GetViewNamesResponse : Response {
        
        private string[] viewNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("viewName")]
        public string[] viewName {
            get {
                return this.viewNameField;
            }
            set {
                this.viewNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class GetViewDefinitionResponse : Response {
        
        private string viewNameField;
        
        private System.DateTime createDateField;
        
        private bool createDateFieldSpecified;
        
        private System.DateTime updateDateField;
        
        private bool updateDateFieldSpecified;
        
        private FieldResponse[] fieldsField;
        
        private ViewOptions viewOptionsField;
        
        /// <remarks/>
        public string viewName {
            get {
                return this.viewNameField;
            }
            set {
                this.viewNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime createDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createDateSpecified {
            get {
                return this.createDateFieldSpecified;
            }
            set {
                this.createDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime updateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updateDateSpecified {
            get {
                return this.updateDateFieldSpecified;
            }
            set {
                this.updateDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("field", IsNullable=false)]
        public FieldResponse[] fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
            }
        }
        
        /// <remarks/>
        public ViewOptions viewOptions {
            get {
                return this.viewOptionsField;
            }
            set {
                this.viewOptionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class FieldOptions {
        
        private bool realValueField;
        
        private bool realValueFieldSpecified;
        
        private int precisionField;
        
        private bool precisionFieldSpecified;
        
        /// <remarks/>
        public bool realValue {
            get {
                return this.realValueField;
            }
            set {
                this.realValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool realValueSpecified {
            get {
                return this.realValueFieldSpecified;
            }
            set {
                this.realValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int precision {
            get {
                return this.precisionField;
            }
            set {
                this.precisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precisionSpecified {
            get {
                return this.precisionFieldSpecified;
            }
            set {
                this.precisionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class Field {
        
        private string mnemonicField;
        
        private FieldOptions fieldOptionsField;
        
        private bool overrideField;
        
        private bool overrideFieldSpecified;
        
        /// <remarks/>
        public string mnemonic {
            get {
                return this.mnemonicField;
            }
            set {
                this.mnemonicField = value;
            }
        }
        
        /// <remarks/>
        public FieldOptions fieldOptions {
            get {
                return this.fieldOptionsField;
            }
            set {
                this.fieldOptionsField = value;
            }
        }
        
        /// <remarks/>
        public bool @override {
            get {
                return this.overrideField;
            }
            set {
                this.overrideField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool overrideSpecified {
            get {
                return this.overrideFieldSpecified;
            }
            set {
                this.overrideFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class CreateOrUpdateViewDefinitionRequest {
        
        private string viewNameField;
        
        private Field[] fieldsField;
        
        private ViewOptions viewOptionsField;
        
        /// <remarks/>
        public string viewName {
            get {
                return this.viewNameField;
            }
            set {
                this.viewNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("field", IsNullable=false)]
        public Field[] fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
            }
        }
        
        /// <remarks/>
        public ViewOptions viewOptions {
            get {
                return this.viewOptionsField;
            }
            set {
                this.viewOptionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class FieldInfo {
        
        private string idField;
        
        private string mnemonicField;
        
        private string descriptionField;
        
        private DLCategory dlCategoryField;
        
        private bool dlCategoryFieldSpecified;
        
        private string definitionField;
        
        private MarketSector[] marketsectorsField;
        
        private int standardWidthField;
        
        private bool standardWidthFieldSpecified;
        
        private int standardDecimalPlacesField;
        
        private bool standardDecimalPlacesFieldSpecified;
        
        private string fieldTypeField;
        
        private bool backofficeField;
        
        private bool backofficeFieldSpecified;
        
        private bool extendedBackofficeField;
        
        private bool extendedBackofficeFieldSpecified;
        
        private System.DateTime productionDateField;
        
        private bool productionDateFieldSpecified;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string mnemonic {
            get {
                return this.mnemonicField;
            }
            set {
                this.mnemonicField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public DLCategory dlCategory {
            get {
                return this.dlCategoryField;
            }
            set {
                this.dlCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dlCategorySpecified {
            get {
                return this.dlCategoryFieldSpecified;
            }
            set {
                this.dlCategoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string definition {
            get {
                return this.definitionField;
            }
            set {
                this.definitionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("marketsectors")]
        public MarketSector[] marketsectors {
            get {
                return this.marketsectorsField;
            }
            set {
                this.marketsectorsField = value;
            }
        }
        
        /// <remarks/>
        public int standardWidth {
            get {
                return this.standardWidthField;
            }
            set {
                this.standardWidthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool standardWidthSpecified {
            get {
                return this.standardWidthFieldSpecified;
            }
            set {
                this.standardWidthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int standardDecimalPlaces {
            get {
                return this.standardDecimalPlacesField;
            }
            set {
                this.standardDecimalPlacesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool standardDecimalPlacesSpecified {
            get {
                return this.standardDecimalPlacesFieldSpecified;
            }
            set {
                this.standardDecimalPlacesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string fieldType {
            get {
                return this.fieldTypeField;
            }
            set {
                this.fieldTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool backoffice {
            get {
                return this.backofficeField;
            }
            set {
                this.backofficeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool backofficeSpecified {
            get {
                return this.backofficeFieldSpecified;
            }
            set {
                this.backofficeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool extendedBackoffice {
            get {
                return this.extendedBackofficeField;
            }
            set {
                this.extendedBackofficeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool extendedBackofficeSpecified {
            get {
                return this.extendedBackofficeFieldSpecified;
            }
            set {
                this.extendedBackofficeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime productionDate {
            get {
                return this.productionDateField;
            }
            set {
                this.productionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool productionDateSpecified {
            get {
                return this.productionDateFieldSpecified;
            }
            set {
                this.productionDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class InstrumentStatus {
        
        private int externalCodeField;
        
        private int internalCodeField;
        
        /// <remarks/>
        public int externalCode {
            get {
                return this.externalCodeField;
            }
            set {
                this.externalCodeField = value;
            }
        }
        
        /// <remarks/>
        public int internalCode {
            get {
                return this.internalCodeField;
            }
            set {
                this.internalCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class InstrumentData {
        
        private InstrumentStatus statusCodeField;
        
        private Instrument instrumentField;
        
        private DataItem[] dataField;
        
        /// <remarks/>
        public InstrumentStatus statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public Instrument instrument {
            get {
                return this.instrumentField;
            }
            set {
                this.instrumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data")]
        public DataItem[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class Instrument {
        
        private string idField;
        
        private MarketSector marketSectorField;
        
        private bool marketSectorFieldSpecified;
        
        private InstrumentIdType idTypeField;
        
        private bool idTypeFieldSpecified;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public MarketSector marketSector {
            get {
                return this.marketSectorField;
            }
            set {
                this.marketSectorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool marketSectorSpecified {
            get {
                return this.marketSectorFieldSpecified;
            }
            set {
                this.marketSectorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public InstrumentIdType idType {
            get {
                return this.idTypeField;
            }
            set {
                this.idTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTypeSpecified {
            get {
                return this.idTypeFieldSpecified;
            }
            set {
                this.idTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public enum InstrumentIdType {
        
        /// <remarks/>
        AUSTRIAN,
        
        /// <remarks/>
        BB_UNIQUE,
        
        /// <remarks/>
        BELGIAN,
        
        /// <remarks/>
        BLOOMBERG,
        
        /// <remarks/>
        CATS,
        
        /// <remarks/>
        CEDEL,
        
        /// <remarks/>
        CINS,
        
        /// <remarks/>
        COMMON_NUMBER,
        
        /// <remarks/>
        CUSIP,
        
        /// <remarks/>
        CZECH,
        
        /// <remarks/>
        DUTCH,
        
        /// <remarks/>
        EUROCLEAR,
        
        /// <remarks/>
        FRENCH,
        
        /// <remarks/>
        IRISH,
        
        /// <remarks/>
        ISIN,
        
        /// <remarks/>
        ISRAELI,
        
        /// <remarks/>
        ITALY,
        
        /// <remarks/>
        JAPAN,
        
        /// <remarks/>
        LUXEMBOURG,
        
        /// <remarks/>
        SEDOL,
        
        /// <remarks/>
        SEDOL2,
        
        /// <remarks/>
        SPAIN,
        
        /// <remarks/>
        TICKER,
        
        /// <remarks/>
        TSCUSIP,
        
        /// <remarks/>
        VALOREN,
        
        /// <remarks/>
        WPK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class ResponseStatus {
        
        private int externalCodeField;
        
        private int internalCodeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public int externalCode {
            get {
                return this.externalCodeField;
            }
            set {
                this.externalCodeField = value;
            }
        }
        
        /// <remarks/>
        public int internalCode {
            get {
                return this.internalCodeField;
            }
            set {
                this.internalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetOverrideFieldsResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetFieldsResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getDataResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class DLWSResponse {
        
        private DLWSHeader dlwsHeaderField;
        
        private ResponseStatus statusCodeField;
        
        /// <remarks/>
        public DLWSHeader dlwsHeader {
            get {
                return this.dlwsHeaderField;
            }
            set {
                this.dlwsHeaderField = value;
            }
        }
        
        /// <remarks/>
        public ResponseStatus statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class GetOverrideFieldsResponse : DLWSResponse {
        
        private string[] sourceFieldsField;
        
        private string[] affectedFieldsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sourceFields")]
        public string[] sourceFields {
            get {
                return this.sourceFieldsField;
            }
            set {
                this.sourceFieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("affectedFields")]
        public string[] affectedFields {
            get {
                return this.affectedFieldsField;
            }
            set {
                this.affectedFieldsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class GetFieldsResponse : DLWSResponse {
        
        private FieldInfo[] fieldsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fields")]
        public FieldInfo[] fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class getDataResponse : DLWSResponse {
        
        private InstrumentData[] instrumentDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("instrumentData")]
        public InstrumentData[] instrumentData {
            get {
                return this.instrumentDataField;
            }
            set {
                this.instrumentDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getDataRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.bloomberg.com/datalicense/dlws/getdata/20071001")]
    public partial class DLWSRequest {
        
        private Instrument[] instrumentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("instruments")]
        public Instrument[] instruments {
            get {
                return this.instrumentsField;
            }
            set {
                this.instrumentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getDataCompletedEventHandler(object sender, getDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getDataResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getDataResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getBloombergDataCompletedEventHandler(object sender, getBloombergDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBloombergDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBloombergDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getDataResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getDataResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void createViewDefinitionCompletedEventHandler(object sender, createViewDefinitionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createViewDefinitionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createViewDefinitionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreateOrUpdateViewDefinitionResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreateOrUpdateViewDefinitionResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getViewDefinitionCompletedEventHandler(object sender, getViewDefinitionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getViewDefinitionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getViewDefinitionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetViewDefinitionResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetViewDefinitionResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getBloombergViewDefinitionCompletedEventHandler(object sender, getBloombergViewDefinitionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBloombergViewDefinitionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBloombergViewDefinitionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetViewDefinitionResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetViewDefinitionResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getViewNamesCompletedEventHandler(object sender, getViewNamesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getViewNamesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getViewNamesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetViewNamesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetViewNamesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getBloombergViewNamesCompletedEventHandler(object sender, getBloombergViewNamesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBloombergViewNamesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBloombergViewNamesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetViewNamesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetViewNamesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void updateViewDefinitionCompletedEventHandler(object sender, updateViewDefinitionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateViewDefinitionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateViewDefinitionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreateOrUpdateViewDefinitionResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreateOrUpdateViewDefinitionResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void deleteViewDefinitionCompletedEventHandler(object sender, deleteViewDefinitionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteViewDefinitionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteViewDefinitionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getFieldsCompletedEventHandler(object sender, getFieldsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFieldsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFieldsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetFieldsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetFieldsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getOverrideFieldsCompletedEventHandler(object sender, getOverrideFieldsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOverrideFieldsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOverrideFieldsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetOverrideFieldsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetOverrideFieldsResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591