//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.ivp.srm.vendorapi.BBFTPServiceLayer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMFTPFileInfo", Namespace="http://schemas.datacontract.org/2004/07/com.ivp.srm.bbgftpservice")]
    [System.SerializableAttribute()]
    public partial class SMFTPFileInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VendorPreferenceIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FolderName {
            get {
                return this.FolderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FolderNameField, value) != true)) {
                    this.FolderNameField = value;
                    this.RaisePropertyChanged("FolderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifier {
            get {
                return this.IdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentifierField, value) != true)) {
                    this.IdentifierField = value;
                    this.RaisePropertyChanged("Identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsError {
            get {
                return this.IsErrorField;
            }
            set {
                if ((this.IsErrorField.Equals(value) != true)) {
                    this.IsErrorField = value;
                    this.RaisePropertyChanged("IsError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VendorPreferenceId {
            get {
                return this.VendorPreferenceIdField;
            }
            set {
                if ((this.VendorPreferenceIdField.Equals(value) != true)) {
                    this.VendorPreferenceIdField = value;
                    this.RaisePropertyChanged("VendorPreferenceId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="com.ivp.srm.bbgftpservice", ConfigurationName="BBFTPServiceLayer.ISRMBbgFtpApi")]
    public interface ISRMBbgFtpApi {
        
        [System.ServiceModel.OperationContractAttribute(Action="com.ivp.srm.bbgftpservice/ISRMBbgFtpApi/RegisterUploadFile", ReplyAction="com.ivp.srm.bbgftpservice/ISRMBbgFtpApi/RegisterUploadFileResponse")]
        bool RegisterUploadFile(out string message, com.ivp.srm.vendorapi.BBFTPServiceLayer.SMFTPFileInfo fileInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.ivp.srm.bbgftpservice/ISRMBbgFtpApi/RegisterDownloadFile", ReplyAction="com.ivp.srm.bbgftpservice/ISRMBbgFtpApi/RegisterDownloadFileResponse")]
        bool RegisterDownloadFile(out string message, com.ivp.srm.vendorapi.BBFTPServiceLayer.SMFTPFileInfo fileInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.ivp.srm.bbgftpservice/ISRMBbgFtpApi/GetUploadFileResponse", ReplyAction="com.ivp.srm.bbgftpservice/ISRMBbgFtpApi/GetUploadFileResponseResponse")]
        bool GetUploadFileResponse(out string message, string identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.ivp.srm.bbgftpservice/ISRMBbgFtpApi/GetDownloadFileResponse", ReplyAction="com.ivp.srm.bbgftpservice/ISRMBbgFtpApi/GetDownloadFileResponseResponse")]
        bool GetDownloadFileResponse(out string message, string identifier);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISRMBbgFtpApiChannel : com.ivp.srm.vendorapi.BBFTPServiceLayer.ISRMBbgFtpApi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SRMBbgFtpApiClient : System.ServiceModel.ClientBase<com.ivp.srm.vendorapi.BBFTPServiceLayer.ISRMBbgFtpApi>, com.ivp.srm.vendorapi.BBFTPServiceLayer.ISRMBbgFtpApi {
        
        public SRMBbgFtpApiClient() {
        }
        
        public SRMBbgFtpApiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SRMBbgFtpApiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SRMBbgFtpApiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SRMBbgFtpApiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegisterUploadFile(out string message, com.ivp.srm.vendorapi.BBFTPServiceLayer.SMFTPFileInfo fileInfo) {
            return base.Channel.RegisterUploadFile(out message, fileInfo);
        }
        
        public bool RegisterDownloadFile(out string message, com.ivp.srm.vendorapi.BBFTPServiceLayer.SMFTPFileInfo fileInfo) {
            return base.Channel.RegisterDownloadFile(out message, fileInfo);
        }
        
        public bool GetUploadFileResponse(out string message, string identifier) {
            return base.Channel.GetUploadFileResponse(out message, identifier);
        }
        
        public bool GetDownloadFileResponse(out string message, string identifier) {
            return base.Channel.GetDownloadFileResponse(out message, identifier);
        }
    }
}
